server:
  port: 9005
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# reactive feign 配置
reactive:
  feign:
    client:
      config:
        producer:
          retry:
            args:
              backoffInMs: 10
              maxRetries: 2
            builder: reactivefeign.ReactiveOptions.Builder

